config/routes.rb
StaticPages::Application.routes.draw do

  get "sessions/new"

  resources :applics
  resources :users
  resources :admins
  resources :servers
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'applics#home'
  
  match "/contact", :to => 'pages#contact'
  
  match "/about", :to => 'pages#about'

  match "/help", :to => 'pages#help'

  match "/signup", :to => 'users#new'
  
  match "/signin", :to => 'sessions#new'

  match "/signout", :to => 'sessions#destroy'

  match "/newadmin", :to => 'admins#new'

  match "/newserver", :to => 'servers#new'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
has_many :servers, :class_name => "Server", :foreign_key => "primary_admin_id"
has_many :servers, :class_name => "Server", :foreign_key => "secondary_admin_id"
end

app/models/applic.rb
class Applic < ActiveRecord::Base
	belongs_to :server
	has_many   :maintainenceactivities
	belongs_to :department
end

app/models/cbreaker.rb
class Cbreaker < ActiveRecord::Base
	belongs_to  :location
	belongs_to  :pdu
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many  :applics
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :server
	belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many  :devices
	has_many  :cbreakers
end

app/models/maintainenceactivity.rb
class Maintainenceactivity < ActiveRecord::Base
	belongs_to :applic
end

app/models/pdu.rb
class Pdu < ActiveRecord::Base
	has_many  :cbreakers
end

app/models/server.rb
class Server < ActiveRecord::Base
	belongs_to :primary_admin, :foreign_key => "primary_admin_id", :class_name => "Admin"
	belongs_to :secondary_admin, :foreign_key => "secondary_admin_id", :class_name => "Admin"
	has_many   :applics
	has_many   :devices
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'digest'

	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence => true, 
	                 :length => { :maximum => 50 }
	validates :email, :presence   => true,
                      :format     => { :with => email_regex },
                      :uniqueness => { :case_sensitive => false }

    validates :password, :presence => true,
              :confirmation => true,
              :length => {:within => 6..40}

    before_save :encrypt_password

    class << self

      def authenticate(email,submitted_password)
        user = find_by_email(email)
        (user && user.has_password?(submitted_password))? user : nil
      end

      def authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt)? user : nil
      end
    end


    def has_password?(submitted_password)
      encrypted_password == encrypt(submitted_password)
    end

    private 
    
    def encrypt_password
      self.salt = make_salt if new_record?
    	self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
    	secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash('#{Time.now.utc}--#{password}')
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def show
		@admin = Admin.find(params[:id])
		@title = @admin.firstnamed
	end

	def new
		@admin = Admin.new
		@title = "New Admin"
	end

	def create
		#raise params[:admin].inspect
		@admin = Admin.new(params[:admin])
		if @admin.save
			redirect_to root_path, :flash => {:success => "New administrator has been created!"}
		else
			@title = "New Admin"
			render 'new'
		end
	end
end

app/controllers/applic_controller.rb
class ApplicController < ApplicationController
  def home
  	@apps = Applic.find(:all)
  end
  def show
  	@app = Applic.find(:params[id])
  	@title = @app.name
  end
end

app/controllers/applics_controller.rb
class ApplicsController < ApplicationController
  def home
  	@apps = Applic.find(:all)
  end
  def show
  	@app = Applic.find(params[:id])
  	@title = @app.name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@title = @user.name
	end

	def new
		@user = User.new
		@title = "Sign up"
	end

	def create
		#raise params[:user].inspect
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			redirect_to @user, :flash => {:success => "Welcome to Sample App!"}
		else
			@title = "Sign up"
			render 'new'
		end
	end

end

app/helpers/applic_helper.rb
module ApplicHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

# title helper

  def title

    basetitle = "CMDB"
    if @title == nil
      basetitle
    else
      "#{basetitle} | #{@title}"
    end
  end

  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		cookies.delete(:remember_token)
		current_user = nil
	end

	private

		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end

		def remember_token
			cookies.signed[:remember_token] || [nil, nil]
		end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
		                                        :class => 'gravatar',
		                                        :gravatar => options)
	end

end

app/views/admins/new.html.erb
<h1>New Server</h1>

<%= form_for(@admin) do |f| %>
	<div class ="field">
		<%= f.label      :firstname %> </br>
		<%= f.text_field :firstname %> </br>
	</div>
	<div class ="field">
		<%= f.label      :lastname %> </br>
		<%= f.text_field :lastname %> </br>
	</div>
	<div class ="field">
		<%= f.label      :email %> </br>
		<%= f.text_field :email %> </br>
	</div>
	<div class ="field">
		<%= f.label      :PersonalEmail %> </br>
		<%= f.text_field :email_personal %> </br>
	</div>
	<div class ="field">
		<%= f.label      :OtherEmail %> </br>
		<%= f.text_field :email_other %> </br>
	</div>
	<div class ="field">
		<%= f.label      :OfficePhone %> </br>
		<%= f.text_field :phone %> </br>
	</div>
	<div class ="field">
		<%= f.label      :PersonalPhone %> </br>
		<%= f.text_field :mobile %> </br>
	</div>
	<div class ="field">
		<%= f.label      :OtherPhone %> </br>
		<%= f.text_field :phone_other %> </br>
	</div>
	<div class ="field">
		<%= f.label      :Pager %> </br>
		<%= f.text_field :pager %> </br>
	</div>
	<div class ="field">
		<%= f.label      :Fax %> </br>
		<%= f.text_field :fax %> </br>
	</div>
	<div class ="field">
		<%= f.label      :PeopleSoftID %> </br>
		<%= f.text_field :ps_id %> </br>
	</div>
	<div class ="field">
		<%= f.label      :CougarnetID %> </br>
		<%= f.text_field :cn_id %> </br>
	</div>
	<div class ="field">
		<%= f.label      :Role %> </br>
		<%= f.text_field :role %> </br>
	</div>
	<div class ="field">
		<%= f.label      :Location %> </br>
		<%= f.text_field :location %> </br>
	</div>
	<div class ="actions">
		<%= f.submit     "Create New Admin" %> </br>
	</div>


<% end %>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", 'http://news.railstutorial.org' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li> <%= link_to "Home", root_path %></li>
			<% if signed_in? %>
			<li> <%= link_to "Profile", current_user %></li>
			<% end%>
			<li> <%= link_to "Help", help_path %></li>
			<% if signed_in? %>
			<li> <%= link_to "Sign out", signout_path %></li>
			<% else %>
			<li> <%= link_to "Sign in", signin_path %></li>
			<% end%>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= render "layouts/stylesheets" %>
</head>
<body>
	<div class="container">
		<%= render "layouts/header" %>
		<section class = "round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>

</p>

app/views/pages/home.html.erb
<h1></h1>
<p></p>

<%= link_to "Sign Up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@user.errors.count, "error") %>
			prohibited this user from being saved:
		</h2>
		<p>There were problem with the following fields:</p>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>